name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Build CSS
        run: npm run build

      - name: Prepare dist folder
        run: |
          mkdir dist
          cp -r src/templates/* dist/
          cp -r src/assets/css dist/css
          cp -r src/assets/images dist/images

      - name: Fix asset paths for GitHub Pages
        run: |
          find dist -name "*.html" -exec sed -i \
            -e 's|href="assets/|href="/flyx-ui/assets/|g' \
            -e 's|src="assets/|src="/flyx-ui/assets/|g' {} +

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.IHARENA_ORG_TOKEN }}
          publish_dir: ./dist
